/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as Verify2faRouteImport } from "./routes/verify-2fa"
import { Route as SuccessRouteImport } from "./routes/success"
import { Route as PricingRouteImport } from "./routes/pricing"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TimeAttendanceIndexRouteImport } from "./routes/time-attendance.index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as ReportsIndexRouteImport } from "./routes/reports/index"
import { Route as PayrollIndexRouteImport } from "./routes/payroll.index"
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding.index"
import { Route as LeaveIndexRouteImport } from "./routes/leave.index"
import { Route as EmployeesIndexRouteImport } from "./routes/employees.index"
import { Route as DepartmentsIndexRouteImport } from "./routes/departments.index"
import { Route as TimeAttendanceClockRouteImport } from "./routes/time-attendance.clock"
import { Route as SettingsSecurityRouteImport } from "./routes/settings/security"
import { Route as SettingsPermissionsRouteImport } from "./routes/settings/permissions"
import { Route as SettingsOrganizationRouteImport } from "./routes/settings/organization"
import { Route as SettingsLicenseRouteImport } from "./routes/settings/license"
import { Route as SettingsJurisdictionsRouteImport } from "./routes/settings/jurisdictions"
import { Route as PayrollNewRouteImport } from "./routes/payroll.new"
import { Route as PayrollPayrollRunIdRouteImport } from "./routes/payroll.$payrollRunId"
import { Route as OnboardingNewRouteImport } from "./routes/onboarding.new"
import { Route as LeaveNewRouteImport } from "./routes/leave.new"
import { Route as LeaveLeaveIdRouteImport } from "./routes/leave.$leaveId"
import { Route as EmployeesNewRouteImport } from "./routes/employees.new"
import { Route as EmployeesEmployeeIdRouteImport } from "./routes/employees.$employeeId"
import { Route as DepartmentsNewRouteImport } from "./routes/departments.new"
import { Route as DepartmentsDepartmentIdRouteImport } from "./routes/departments.$departmentId"

const Verify2faRoute = Verify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: "/success",
  path: "/success",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TimeAttendanceIndexRoute = TimeAttendanceIndexRouteImport.update({
  id: "/time-attendance/",
  path: "/time-attendance/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: "/reports/",
  path: "/reports/",
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: "/payroll/",
  path: "/payroll/",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/onboarding/",
  path: "/onboarding/",
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: "/leave/",
  path: "/leave/",
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: "/employees/",
  path: "/employees/",
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: "/departments/",
  path: "/departments/",
  getParentRoute: () => rootRouteImport,
} as any)
const TimeAttendanceClockRoute = TimeAttendanceClockRouteImport.update({
  id: "/time-attendance/clock",
  path: "/time-attendance/clock",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: "/settings/security",
  path: "/settings/security",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: "/settings/permissions",
  path: "/settings/permissions",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: "/settings/organization",
  path: "/settings/organization",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLicenseRoute = SettingsLicenseRouteImport.update({
  id: "/settings/license",
  path: "/settings/license",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsJurisdictionsRoute = SettingsJurisdictionsRouteImport.update({
  id: "/settings/jurisdictions",
  path: "/settings/jurisdictions",
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollNewRoute = PayrollNewRouteImport.update({
  id: "/payroll/new",
  path: "/payroll/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollPayrollRunIdRoute = PayrollPayrollRunIdRouteImport.update({
  id: "/payroll/$payrollRunId",
  path: "/payroll/$payrollRunId",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNewRoute = OnboardingNewRouteImport.update({
  id: "/onboarding/new",
  path: "/onboarding/new",
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveNewRoute = LeaveNewRouteImport.update({
  id: "/leave/new",
  path: "/leave/new",
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveLeaveIdRoute = LeaveLeaveIdRouteImport.update({
  id: "/leave/$leaveId",
  path: "/leave/$leaveId",
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: "/employees/new",
  path: "/employees/new",
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: "/employees/$employeeId",
  path: "/employees/$employeeId",
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsNewRoute = DepartmentsNewRouteImport.update({
  id: "/departments/new",
  path: "/departments/new",
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: "/departments/$departmentId",
  path: "/departments/$departmentId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/pricing": typeof PricingRoute
  "/success": typeof SuccessRoute
  "/verify-2fa": typeof Verify2faRoute
  "/departments/$departmentId": typeof DepartmentsDepartmentIdRoute
  "/departments/new": typeof DepartmentsNewRoute
  "/employees/$employeeId": typeof EmployeesEmployeeIdRoute
  "/employees/new": typeof EmployeesNewRoute
  "/leave/$leaveId": typeof LeaveLeaveIdRoute
  "/leave/new": typeof LeaveNewRoute
  "/onboarding/new": typeof OnboardingNewRoute
  "/payroll/$payrollRunId": typeof PayrollPayrollRunIdRoute
  "/payroll/new": typeof PayrollNewRoute
  "/settings/jurisdictions": typeof SettingsJurisdictionsRoute
  "/settings/license": typeof SettingsLicenseRoute
  "/settings/organization": typeof SettingsOrganizationRoute
  "/settings/permissions": typeof SettingsPermissionsRoute
  "/settings/security": typeof SettingsSecurityRoute
  "/time-attendance/clock": typeof TimeAttendanceClockRoute
  "/departments/": typeof DepartmentsIndexRoute
  "/employees/": typeof EmployeesIndexRoute
  "/leave/": typeof LeaveIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/payroll/": typeof PayrollIndexRoute
  "/reports/": typeof ReportsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/time-attendance/": typeof TimeAttendanceIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/pricing": typeof PricingRoute
  "/success": typeof SuccessRoute
  "/verify-2fa": typeof Verify2faRoute
  "/departments/$departmentId": typeof DepartmentsDepartmentIdRoute
  "/departments/new": typeof DepartmentsNewRoute
  "/employees/$employeeId": typeof EmployeesEmployeeIdRoute
  "/employees/new": typeof EmployeesNewRoute
  "/leave/$leaveId": typeof LeaveLeaveIdRoute
  "/leave/new": typeof LeaveNewRoute
  "/onboarding/new": typeof OnboardingNewRoute
  "/payroll/$payrollRunId": typeof PayrollPayrollRunIdRoute
  "/payroll/new": typeof PayrollNewRoute
  "/settings/jurisdictions": typeof SettingsJurisdictionsRoute
  "/settings/license": typeof SettingsLicenseRoute
  "/settings/organization": typeof SettingsOrganizationRoute
  "/settings/permissions": typeof SettingsPermissionsRoute
  "/settings/security": typeof SettingsSecurityRoute
  "/time-attendance/clock": typeof TimeAttendanceClockRoute
  "/departments": typeof DepartmentsIndexRoute
  "/employees": typeof EmployeesIndexRoute
  "/leave": typeof LeaveIndexRoute
  "/onboarding": typeof OnboardingIndexRoute
  "/payroll": typeof PayrollIndexRoute
  "/reports": typeof ReportsIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/time-attendance": typeof TimeAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/pricing": typeof PricingRoute
  "/success": typeof SuccessRoute
  "/verify-2fa": typeof Verify2faRoute
  "/departments/$departmentId": typeof DepartmentsDepartmentIdRoute
  "/departments/new": typeof DepartmentsNewRoute
  "/employees/$employeeId": typeof EmployeesEmployeeIdRoute
  "/employees/new": typeof EmployeesNewRoute
  "/leave/$leaveId": typeof LeaveLeaveIdRoute
  "/leave/new": typeof LeaveNewRoute
  "/onboarding/new": typeof OnboardingNewRoute
  "/payroll/$payrollRunId": typeof PayrollPayrollRunIdRoute
  "/payroll/new": typeof PayrollNewRoute
  "/settings/jurisdictions": typeof SettingsJurisdictionsRoute
  "/settings/license": typeof SettingsLicenseRoute
  "/settings/organization": typeof SettingsOrganizationRoute
  "/settings/permissions": typeof SettingsPermissionsRoute
  "/settings/security": typeof SettingsSecurityRoute
  "/time-attendance/clock": typeof TimeAttendanceClockRoute
  "/departments/": typeof DepartmentsIndexRoute
  "/employees/": typeof EmployeesIndexRoute
  "/leave/": typeof LeaveIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/payroll/": typeof PayrollIndexRoute
  "/reports/": typeof ReportsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/time-attendance/": typeof TimeAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/pricing"
    | "/success"
    | "/verify-2fa"
    | "/departments/$departmentId"
    | "/departments/new"
    | "/employees/$employeeId"
    | "/employees/new"
    | "/leave/$leaveId"
    | "/leave/new"
    | "/onboarding/new"
    | "/payroll/$payrollRunId"
    | "/payroll/new"
    | "/settings/jurisdictions"
    | "/settings/license"
    | "/settings/organization"
    | "/settings/permissions"
    | "/settings/security"
    | "/time-attendance/clock"
    | "/departments/"
    | "/employees/"
    | "/leave/"
    | "/onboarding/"
    | "/payroll/"
    | "/reports/"
    | "/settings/"
    | "/time-attendance/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/pricing"
    | "/success"
    | "/verify-2fa"
    | "/departments/$departmentId"
    | "/departments/new"
    | "/employees/$employeeId"
    | "/employees/new"
    | "/leave/$leaveId"
    | "/leave/new"
    | "/onboarding/new"
    | "/payroll/$payrollRunId"
    | "/payroll/new"
    | "/settings/jurisdictions"
    | "/settings/license"
    | "/settings/organization"
    | "/settings/permissions"
    | "/settings/security"
    | "/time-attendance/clock"
    | "/departments"
    | "/employees"
    | "/leave"
    | "/onboarding"
    | "/payroll"
    | "/reports"
    | "/settings"
    | "/time-attendance"
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/pricing"
    | "/success"
    | "/verify-2fa"
    | "/departments/$departmentId"
    | "/departments/new"
    | "/employees/$employeeId"
    | "/employees/new"
    | "/leave/$leaveId"
    | "/leave/new"
    | "/onboarding/new"
    | "/payroll/$payrollRunId"
    | "/payroll/new"
    | "/settings/jurisdictions"
    | "/settings/license"
    | "/settings/organization"
    | "/settings/permissions"
    | "/settings/security"
    | "/time-attendance/clock"
    | "/departments/"
    | "/employees/"
    | "/leave/"
    | "/onboarding/"
    | "/payroll/"
    | "/reports/"
    | "/settings/"
    | "/time-attendance/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SuccessRoute: typeof SuccessRoute
  Verify2faRoute: typeof Verify2faRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  DepartmentsNewRoute: typeof DepartmentsNewRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  LeaveLeaveIdRoute: typeof LeaveLeaveIdRoute
  LeaveNewRoute: typeof LeaveNewRoute
  OnboardingNewRoute: typeof OnboardingNewRoute
  PayrollPayrollRunIdRoute: typeof PayrollPayrollRunIdRoute
  PayrollNewRoute: typeof PayrollNewRoute
  SettingsJurisdictionsRoute: typeof SettingsJurisdictionsRoute
  SettingsLicenseRoute: typeof SettingsLicenseRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  TimeAttendanceClockRoute: typeof TimeAttendanceClockRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TimeAttendanceIndexRoute: typeof TimeAttendanceIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-2fa": {
      id: "/verify-2fa"
      path: "/verify-2fa"
      fullPath: "/verify-2fa"
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/success": {
      id: "/success"
      path: "/success"
      fullPath: "/success"
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing": {
      id: "/pricing"
      path: "/pricing"
      fullPath: "/pricing"
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/time-attendance/": {
      id: "/time-attendance/"
      path: "/time-attendance"
      fullPath: "/time-attendance/"
      preLoaderRoute: typeof TimeAttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports/": {
      id: "/reports/"
      path: "/reports"
      fullPath: "/reports/"
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payroll/": {
      id: "/payroll/"
      path: "/payroll"
      fullPath: "/payroll/"
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/": {
      id: "/onboarding/"
      path: "/onboarding"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/leave/": {
      id: "/leave/"
      path: "/leave"
      fullPath: "/leave/"
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/employees/": {
      id: "/employees/"
      path: "/employees"
      fullPath: "/employees/"
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/departments/": {
      id: "/departments/"
      path: "/departments"
      fullPath: "/departments/"
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/time-attendance/clock": {
      id: "/time-attendance/clock"
      path: "/time-attendance/clock"
      fullPath: "/time-attendance/clock"
      preLoaderRoute: typeof TimeAttendanceClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/security": {
      id: "/settings/security"
      path: "/settings/security"
      fullPath: "/settings/security"
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/permissions": {
      id: "/settings/permissions"
      path: "/settings/permissions"
      fullPath: "/settings/permissions"
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/organization": {
      id: "/settings/organization"
      path: "/settings/organization"
      fullPath: "/settings/organization"
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/license": {
      id: "/settings/license"
      path: "/settings/license"
      fullPath: "/settings/license"
      preLoaderRoute: typeof SettingsLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/jurisdictions": {
      id: "/settings/jurisdictions"
      path: "/settings/jurisdictions"
      fullPath: "/settings/jurisdictions"
      preLoaderRoute: typeof SettingsJurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payroll/new": {
      id: "/payroll/new"
      path: "/payroll/new"
      fullPath: "/payroll/new"
      preLoaderRoute: typeof PayrollNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payroll/$payrollRunId": {
      id: "/payroll/$payrollRunId"
      path: "/payroll/$payrollRunId"
      fullPath: "/payroll/$payrollRunId"
      preLoaderRoute: typeof PayrollPayrollRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/new": {
      id: "/onboarding/new"
      path: "/onboarding/new"
      fullPath: "/onboarding/new"
      preLoaderRoute: typeof OnboardingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/leave/new": {
      id: "/leave/new"
      path: "/leave/new"
      fullPath: "/leave/new"
      preLoaderRoute: typeof LeaveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/leave/$leaveId": {
      id: "/leave/$leaveId"
      path: "/leave/$leaveId"
      fullPath: "/leave/$leaveId"
      preLoaderRoute: typeof LeaveLeaveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/employees/new": {
      id: "/employees/new"
      path: "/employees/new"
      fullPath: "/employees/new"
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/employees/$employeeId": {
      id: "/employees/$employeeId"
      path: "/employees/$employeeId"
      fullPath: "/employees/$employeeId"
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/departments/new": {
      id: "/departments/new"
      path: "/departments/new"
      fullPath: "/departments/new"
      preLoaderRoute: typeof DepartmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/departments/$departmentId": {
      id: "/departments/$departmentId"
      path: "/departments/$departmentId"
      fullPath: "/departments/$departmentId"
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SuccessRoute: SuccessRoute,
  Verify2faRoute: Verify2faRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  DepartmentsNewRoute: DepartmentsNewRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  LeaveLeaveIdRoute: LeaveLeaveIdRoute,
  LeaveNewRoute: LeaveNewRoute,
  OnboardingNewRoute: OnboardingNewRoute,
  PayrollPayrollRunIdRoute: PayrollPayrollRunIdRoute,
  PayrollNewRoute: PayrollNewRoute,
  SettingsJurisdictionsRoute: SettingsJurisdictionsRoute,
  SettingsLicenseRoute: SettingsLicenseRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  TimeAttendanceClockRoute: TimeAttendanceClockRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  LeaveIndexRoute: LeaveIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PayrollIndexRoute: PayrollIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TimeAttendanceIndexRoute: TimeAttendanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
