/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file, as it will be overwritten.
// However, due to Zod v4 incompatibility, this is a manually maintained file.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as DashboardRoute } from "./routes/dashboard";
import { Route as SuccessRoute } from "./routes/success";
import { Route as DepartmentsIndexRoute } from "./routes/departments.index";
import { Route as EmployeesIndexRoute } from "./routes/employees.index";
import { Route as PayrollIndexRoute } from "./routes/payroll.index";
import { Route as PayrollNewRoute } from "./routes/payroll.new";
import { Route as PayrollDetailRoute } from "./routes/payroll.$payrollRunId";
import { Route as ReportsIndexRoute } from "./routes/reports/index";
import { Route as SettingsOrganizationRoute } from "./routes/settings/organization";
import { Route as SettingsJurisdictionsRoute } from "./routes/settings/jurisdictions";
import { Route as SettingsPermissionsRoute } from "./routes/settings/permissions";

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			preLoaderRoute: typeof IndexRoute;
			parentRoute: typeof rootRoute;
		};
		"/login": {
			preLoaderRoute: typeof LoginRoute;
			parentRoute: typeof rootRoute;
		};
		"/dashboard": {
			preLoaderRoute: typeof DashboardRoute;
			parentRoute: typeof rootRoute;
		};
		"/success": {
			preLoaderRoute: typeof SuccessRoute;
			parentRoute: typeof rootRoute;
		};
		"/departments/": {
			preLoaderRoute: typeof DepartmentsIndexRoute;
			parentRoute: typeof rootRoute;
		};
		"/employees/": {
			preLoaderRoute: typeof EmployeesIndexRoute;
			parentRoute: typeof rootRoute;
		};
		"/payroll/": {
			preLoaderRoute: typeof PayrollIndexRoute;
			parentRoute: typeof rootRoute;
		};
		"/payroll/new": {
			preLoaderRoute: typeof PayrollNewRoute;
			parentRoute: typeof rootRoute;
		};
		"/payroll/$payrollRunId": {
			preLoaderRoute: typeof PayrollDetailRoute;
			parentRoute: typeof rootRoute;
		};
		"/reports/": {
			preLoaderRoute: typeof ReportsIndexRoute;
			parentRoute: typeof rootRoute;
		};
		"/settings/organization": {
			preLoaderRoute: typeof SettingsOrganizationRoute;
			parentRoute: typeof rootRoute;
		};
		"/settings/jurisdictions": {
			preLoaderRoute: typeof SettingsJurisdictionsRoute;
			parentRoute: typeof rootRoute;
		};
		"/settings/permissions": {
			preLoaderRoute: typeof SettingsPermissionsRoute;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree
const rootRouteChildren = {
	IndexRoute: IndexRoute,
	LoginRoute: LoginRoute,
	DashboardRoute: DashboardRoute,
	SuccessRoute: SuccessRoute,
	DepartmentsIndexRoute: DepartmentsIndexRoute,
	EmployeesIndexRoute: EmployeesIndexRoute,
	PayrollIndexRoute: PayrollIndexRoute,
	PayrollNewRoute: PayrollNewRoute,
	PayrollDetailRoute: PayrollDetailRoute,
	ReportsIndexRoute: ReportsIndexRoute,
	SettingsOrganizationRoute: SettingsOrganizationRoute,
	SettingsJurisdictionsRoute: SettingsJurisdictionsRoute,
	SettingsPermissionsRoute: SettingsPermissionsRoute,
};

export const routeTree = rootRoute.addChildren([
	IndexRoute,
	LoginRoute,
	DashboardRoute,
	SuccessRoute,
	DepartmentsIndexRoute,
	EmployeesIndexRoute,
	PayrollIndexRoute,
	PayrollNewRoute,
	PayrollDetailRoute,
	ReportsIndexRoute,
	SettingsOrganizationRoute,
	SettingsJurisdictionsRoute,
	SettingsPermissionsRoute,
]);
